build_from:
  aarch64: homeassistant/aarch64-base:3.18
  amd64: homeassistant/amd64-base:3.18
  armv7: homeassistant/armv7-base:3.18
labels:
  org.opencontainers.image.title: "rtl_433 Home Assistant Add-on"
  org.opencontainers.image.description: "Receive wireless sensor data via an SDR dongle and rtl_433"
  org.opencontainers.image.source: "https://github.com/catduckgnaf/rtl_433_haos_addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  rtl433GitRevision: master
